# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Portfolio.create([
	{title: "Antony Morato", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim.", url: "http://www.morato.it"},
	{title: "Armani Jeans", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim.", url: "www.armani.com/Armani-Jeans"},
	{title: "Atos Lombardini", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Axara", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Basler", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Coccinelle", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Fabi", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Furla", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Kocca", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Laurel", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Lauren", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Liu Jo", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Liviana Conti", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Love Moschino", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Luciano Barachini", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Luisa Spagnoli", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Manila Grace", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Patrizia Pepe", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Pinko", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Piquardo", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Pura Lopez", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim. Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Silvian Heach", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Tosca Blu", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Tru Trussardi", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Tru Trussardi Jeans", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Twin-Set", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Valentino", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."},
	{title: "Antony Morato", content: "Lorem ipsum dolor sit amet, eos ut iusto evertitur honestatis. Debet inimicus molestiae qui no, et quaeque nonumes vim. Ad affert molestie partiendo mei, pri graece salutatus ad. Et idque labitur omnesque has. Dolore quaeque propriae ne eos, falli denique consequuntur nec te. Nonumy dissentias consequuntur in vim."}
])